# name: Docker Compose Actions Workflow
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps: 
#     - uses: actions/checkout@master
#     - uses: actions/toolkit@master
#     - name: Build the stack
#       run: docker-compose up -d
#     - name: Run the Tests
#       run: |
#         docker-compose exec users python recreate_db
#         docker-compose exec users python manage.py seed_db
#         docker-compose exec users python manage.py test
#         docker-compose exec users flake8 project
#     - name: Seed DB
#       run: 
#     - name: Run Python Tests
#       run: docker-compose exec users python manage.py test
#     - name: Run Python Lint Test
#       run: docker-compose exec users flake8 project
